stages:
  - build_and_push

variables:
  AWS_DEFAULT_REGION: us-east-2
  ECR_REGISTRY: 589535355002.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPO: 589535355002.dkr.ecr.us-east-2.amazonaws.com/careerops

  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_and_push:
  stage: build_and_push
  image: docker:latest

  services:
    - name: docker:dind
      alias: docker

  before_script:
    - apk add --no-cache aws-cli
    - aws sts get-caller-identity
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" |
        docker login --username AWS --password-stdin "$ECR_REGISTRY"

  script:
    - docker info
    - docker buildx build
        --platform linux/amd64
        --provenance=false
        --push
        -t "$ECR_REPO:latest"
        -t "$ECR_REPO:$CI_COMMIT_SHORT_SHA"
        .

  only:
    - main